# Generated by Django 3.2.4 on 2021-08-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210821_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
