# Generated by Django 3.2.4 on 2021-09-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('f', 'f'), ('m', 'm'), ('u', 'u')], max_length=1),
        ),
    ]
