# Generated by Django 3.2.4 on 2021-09-05 09:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210904_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('4/37', '4/37'), ('5/38', '5/38'), ('6/39', '6/39'), ('7/41', '7/41'), ('8/42', '8/42'), ('9/43', '9/43'), ('10/44', '10/44'), ('11/45', '11/45'), ('11.5/46', '11.5/46')], max_length=49, null=True),
        ),
    ]
