# Generated by Django 3.2.4 on 2021-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
